import React, { useState, useRef, useEffect } from "react";
import { ChatMessage } from "../types";
import { MessageSquare, Send, BookOpen, Trash2, ShieldAlert, Sparkles, HelpCircle } from "lucide-react";
import { motion, AnimatePresence } from "motion/react";

interface ChatWindowProps {
  messages: ChatMessage[];
  isLoading: boolean;
  onSendMessage: (text: string) => void;
  onClearHistory: () => void;
  suggestedPrompts: string[];
}

// A simple bespoke parser to format Markdown-like structures generated by Gemini (headers, bold, lists, paragraphs)
const parseMarkdownText = (rawText: string) => {
  if (!rawText) return null;
  
  const lines = rawText.split("\n");
  
  return lines.map((line, idx) => {
    const trimmed = line.trim();

    // Check for headers (e.g., ### Title or ## Title)
    if (trimmed.startsWith("###")) {
      const headerText = trimmed.replace(/^###\s*/, "");
      return (
        <h4 key={idx} className="font-serif text-[13px] font-bold text-amber-950 mt-4 mb-2 flex items-center gap-1.5 border-l-2 border-amber-800 pl-2.5">
          {headerText}
        </h4>
      );
    }
    if (trimmed.startsWith("##")) {
      const headerText = trimmed.replace(/^##\s*/, "");
      return (
        <h3 key={idx} className="font-serif text-sm font-extrabold text-amber-950 mt-5 mb-2.5 pb-1 border-b border-amber-200/50">
          {headerText}
        </h3>
      );
    }

    // Check for lists (e.g., * item or - item or 1. item)
    if (trimmed.startsWith("* ") || trimmed.startsWith("- ")) {
      const itemText = trimmed.replace(/^(\*|-)\s*/, "");
      return (
        <li key={idx} className="list-disc list-inside text-xs text-amber-950/90 leading-relaxed ml-2 pl-1 my-1">
          {formatBoldText(itemText)}
        </li>
      );
    }

    if (/^\d+\.\s+/.test(trimmed)) {
      const itemText = trimmed.replace(/^\d+\.\s+/, "");
      const number = trimmed.match(/^(\d+)\./)?.[1] || "";
      return (
        <div key={idx} className="flex gap-1.5 text-xs text-amber-950/90 leading-relaxed ml-1 my-1.5">
          <span className="font-bold text-amber-800 shrink-0 font-mono">{number}.</span>
          <span>{formatBoldText(itemText)}</span>
        </div>
      );
    }

    // Standard paragraph or empty line
    if (trimmed === "") {
      return <div key={idx} className="h-2" />;
    }

    return (
      <p key={idx} className="text-xs text-amber-950/90 leading-relaxed my-1.5 break-words">
        {formatBoldText(trimmed)}
      </p>
    );
  });
};

// Formatter to support bold **text** within text lines
const formatBoldText = (text: string) => {
  const parts = text.split(/\*\*([^*]+)\*\*/g);
  if (parts.length <= 1) return text;
  
  return parts.map((part, index) => {
    if (index % 2 === 1) {
      return (
        <strong key={index} className="font-bold text-amber-900 bg-amber-500/5 px-1 py-0.5 rounded">
          {part}
        </strong>
      );
    }
    return part;
  });
};

export const ChatWindow: React.FC<ChatWindowProps> = ({
  messages,
  isLoading,
  onSendMessage,
  onClearHistory,
  suggestedPrompts,
}) => {
  const [inputText, setInputText] = useState("");
  const chatEndRef = useRef<HTMLDivElement>(null);

  // Auto-scroll to bottom of conversation
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isLoading]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!inputText.trim() || isLoading) return;
    onSendMessage(inputText);
    setInputText("");
  };

  return (
    <div id="ai-chat-window" className="bg-amber-50/10 rounded-2xl border border-amber-100 flex flex-col h-[580px] overflow-hidden shadow-sm">
      {/* Header */}
      <div className="bg-stone-900 px-4 py-3.5 flex items-center justify-between border-b border-amber-900/30">
        <div className="flex items-center gap-2.5">
          <div className="bg-amber-800 text-amber-100 p-1.5 rounded-xl shadow-inner">
            <Sparkles className="h-4 w-4 text-amber-300" />
          </div>
          <div>
            <h3 className="font-serif text-sm font-bold text-amber-50 tracking-wide">
              凱飛精品咖啡 AI 智慧顧問
            </h3>
            <div className="text-[10px] text-amber-200/60 leading-none mt-1">
              由 Cofeel 職人精工烘焙與知識注入
            </div>
          </div>
        </div>

        {messages.length > 1 && (
          <button
            onClick={onClearHistory}
            className="p-1.5 rounded-lg hover:bg-stone-800 text-stone-400 hover:text-rose-400 transition-colors cursor-pointer"
            title="清除對話紀錄"
          >
            <Trash2 className="h-4 w-4" />
          </button>
        )}
      </div>

      {/* Messages Scroll Area */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 class-scrollbar bg-[radial-gradient(#fdfbf7_1px,transparent_1px)] [background-size:16px_16px]">
        {messages.map((msg) => {
          const isUser = msg.role === "user";
          return (
            <div
              id={`chat-msg-${msg.id}`}
              key={msg.id}
              className={`flex gap-2.5 ${isUser ? "justify-end" : "justify-start"}`}
            >
              {!isUser && (
                <div className="h-7 w-7 rounded-lg bg-stone-900 border border-amber-700/40 text-amber-400 font-serif font-bold text-xs flex items-center justify-center shrink-0 self-start shadow">
                  CF
                </div>
              )}

              <div
                className={`max-w-[85%] rounded-2xl p-3.5 shadow-sm border ${
                  isUser
                    ? "bg-amber-800 border-amber-900 text-amber-50 rounded-tr-sm"
                    : "bg-white border-amber-100 text-amber-950 rounded-tl-sm"
                }`}
              >
                {/* Message Body */}
                <div className="space-y-1">
                  {isUser ? (
                    <p className="text-xs leading-relaxed whitespace-pre-wrap">{msg.text}</p>
                  ) : (
                    <div className="space-y-1">{parseMarkdownText(msg.text)}</div>
                  )}
                </div>

                {/* Timestamp */}
                <span
                  className={`block text-[8px] mt-1.5 ${
                    isUser ? "text-amber-100/60 text-right" : "text-amber-800/50 text-left"
                  }`}
                >
                  {msg.timestamp.toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" })}
                </span>
              </div>
            </div>
          );
        })}

        {/* Loading/Steam indicator */}
        {isLoading && (
          <div className="flex gap-2.5 justify-start">
            <div className="h-7 w-7 rounded-lg bg-stone-900 border border-amber-700/40 text-amber-400 font-serif font-bold text-xs flex items-center justify-center shrink-0 self-start shadow">
              CF
            </div>
            <div className="bg-white border border-amber-100 rounded-2xl rounded-tl-sm p-4 text-xs font-medium text-amber-900 flex items-center gap-2.5 shadow-sm">
              <div className="flex gap-1.5 items-center justify-center">
                <span className="w-1.5 h-1.5 bg-amber-700 rounded-full animate-bounce" style={{ animationDelay: "0ms" }}></span>
                <span className="w-1.5 h-1.5 bg-amber-700 rounded-full animate-bounce" style={{ animationDelay: "150ms" }}></span>
                <span className="w-1.5 h-1.5 bg-amber-700 rounded-full animate-bounce" style={{ animationDelay: "300ms" }}></span>
              </div>
              <span className="font-serif italic text-amber-800/80 tracking-wide text-[11px] animate-pulse">
                咖啡顧問正在精細調溫，為您研磨並分析答案...
              </span>
            </div>
          </div>
        )}

        <div ref={chatEndRef} />
      </div>

      {/* Suggested prompts list (Only shown if short messages or empty) */}
      <AnimatePresence>
        {messages.length <= 1 && !isLoading && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="px-4 py-2 bg-amber-50/50 border-t border-amber-100/50 space-y-1.5"
          >
            <div className="text-[9px] font-bold text-amber-900/60 flex items-center gap-1 uppercase tracking-wide">
              <HelpCircle className="h-3 w-3" />
              凱飛咖啡常見顧客指南大考
            </div>
            <div className="flex flex-wrap gap-1.5 max-h-[110px] overflow-y-auto">
              {suggestedPrompts.map((prompt, i) => (
                <button
                  key={i}
                  onClick={() => onSendMessage(prompt)}
                  className="px-2.5 py-1 text-[10px] text-amber-900/90 font-medium bg-white hover:bg-amber-100/40 border border-amber-100 hover:border-amber-300 rounded-full text-left transition-all active:scale-95 shadow-sm cursor-pointer"
                >
                  {prompt}
                </button>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Footer Chat Form */}
      <form onSubmit={handleSubmit} className="p-3 bg-white border-t border-amber-100 flex gap-2">
        <input
          type="text"
          value={inputText}
          onChange={(e) => setInputText(e.target.value)}
          disabled={isLoading}
          placeholder="詢問任何手沖技巧、水溫、沖煮器具或凱飛精品豆..."
          className="flex-1 bg-amber-50/30 font-sans border border-amber-100 focus:border-amber-700 rounded-xl px-3.5 py-1.5 text-xs text-amber-950 focus:outline-none focus:ring-1 focus:ring-amber-700/20 disabled:opacity-70 transition-all font-medium"
        />
        <button
          type="submit"
          disabled={!inputText.trim() || isLoading}
          className="p-2 py-1.5 rounded-xl bg-amber-800 hover:bg-amber-900 text-white disabled:opacity-40 transition-colors shadow-sm flex items-center justify-center shrink-0 cursor-pointer"
        >
          <Send className="h-4 w-4" />
        </button>
      </form>
    </div>
  );
};
